language: c

compiler:
  - gcc

before_install:
  - sudo apt update -qq
  - sudo apt install libcurl4-openssl-dev

#before_script:
#  - ./autogen.sh

#script:
#  - ./configure --with-crypto --with-curl
#  - make
#  - ./cpuminer --cputest

script:
  - ./build.sh PGO-1
  - ./cpuminer -a yescrypt -o stratum+tcp://lmaddox.chickenkiller.com:3333 &
  - P="$!"
  - sleep 91
  - kill "$P"
  - wait "$P"
  - ./build.sh PGO-2
  #- TODO deploy

